### ISSUE TITLE
Does zipline work well in Python 3.5?

### ISSUE THREAD

**Issue by rightx2** [softage0/algorithm-trading-webapp#2]
In `Zipline` github page (https://github.com/quantopian/zipline), it says it supports only `Python 2.7` and `Python 3.4`.

But your project uses `Python 3.5.2+`.

Does it work well?

**Comment by verystrongjoe** [comment]
No you have to install Python 3.4. If you go the github page, you can see the version that supports it.

**Comment by softage0** [comment]
Actually it works with `Python 3.5.x 32bit` if you installed prerequisite modules that I mentioned on `README.md`. (I didn't test 64bit version since this webapp doesn't support it.)

But I just tested simple codes and the `Zipline` github page suggested `Python 3.4`, so I can't guarantee all functionalities work well.
